export const ROUTES = {
  HOME: "/",
  CART: "/cart",
  PAYMENT_SUCCESS: "/payment-success",
  ORDER: "/orders",
  RETURN: "/return",
  RETURN_REVIEW: "/return-preview",
  RETURN_HISTORY: "/return-history",
  RETURN_SUCCESS: "/return-success",
  RETURN_DETAIL: (id: string) => `/return/${id}`,
  ORDER_DETAIL: (id) => `/orders/${id}`,
  PRODUCT_DETAIL: (id) => `/products/${id}`,
  USER_ADDRESS: "/addresses",
  USER_ADDRESS_ADD: "/addresses-add",
  USER_ADDRESS_EDIT: `/addresses-edit`,
  NOT_FOUND: "*",
  NOTIFICATION: (id) => `/notification/${id}`,
  COMMISSION: "/commission",
  MEMBER_CARD: "/member-card",
  RESULT: "/result",
  SEARCH: "/search",
  SEARCH_RESULT: "/search-result",
  INCOME: "/income",
  REQUEST_COMMISSION: "/request-commission",
  BANK_ACCOUNT: "/bank-account",
  SHIPPING: "/shipping",
  SHIPPING_DETAIL: "/shipping-detail",
  CTV_USER_LIST: "/ctv-user-list",

  BUY_VOUCHER: "/buy-voucher",
  USER_VOUCHER: "/user-voucher",
};
